[TW-01] landing page
serudda/twon pull request #11
Opened 2023-05-04 19:39 UTC by Zyruks

## Changes Made 🎉

- [x] feat: add fluid font sizes, custom colors, animation, Card, Counter, Typewriter components
- [x] chore: add Twitter icons, update TextGradient interface, add utility classes for animation delay
- [x] feat(home): redesign landing page

### Describe Changes

This PR adds several new features and improvements to the project:

- **Fluid font sizes, custom colors, and animation:** The theme now supports fluid font sizes and custom colors, as well as a new fade-in animation. 
- **Card and Counter components:** Two new components have been added: Card displays tweet-like cards with tweet content and engagement metrics, while Counter displays a count that increments from one number to another.
- **Typewriter component:** A new Typewriter component has been added, which can be used to display text with a typewriter effect.
- **Twitter icons:** Several Twitter icons have been added to the project.
- **TextGradient interface update:** The TextGradient interface has been updated to accept arbitrary values.
- **Utility classes for animation delay:** New utility classes have been added to allow for custom animation delays.
- **Redesigned landing page:** The landing page has been redesigned with a more modern layout, featuring a typewriter effect and a Side-UI TextInput component for logging in with Discord.

### Related Issue(s)

This PR addresses the following issue:

- #1 

## Visuals (Optional)
![Screen Shot 2023-05-04 at 15 37 56](https://user-images.githubusercontent.com/14036522/236311742-07a3c69d-9295-4125-8432-d39cd9c18de3.png)

![image](https://user-images.githubusercontent.com/14036522/236311702-1c40dcb2-7d7f-453f-a1f2-d2ea6cb02b2b.png)

### Checklist ✅

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-05-05 22:05 UTC, serudda requested changes
Bello PR...

2023-05-05 22:05 UTC, serudda commented on apps/nextjs/src/pages/index.tsx
> +      <main className="relative flex h-full w-full flex-none flex-col items-center justify-between gap-16  overflow-hidden bg-black p-10 ">
veo que siempre se te queda un espacio al final en el className

2023-05-05 22:05 UTC, serudda commented on apps/nextjs/src/pages/index.tsx
> +        <section className=" animate-fade-in  z-10 flex flex-col items-center gap-12 text-white opacity-0 ">
veo que siempre se te queda un espacio al final en el className

2023-05-05 22:05 UTC, serudda commented on apps/nextjs/src/styles/globals.css
> +}
```suggestion
@layer utilities {
  .animation-delay-500 {
    animation-delay: 500ms;
  }
  
  .animation-delay-1000 {
    animation-delay: 1000ms;
  }
}
```

2023-05-05 22:05 UTC, serudda commented on apps/nextjs/src/styles/globals.css
> +}
Por sugerencia de TailwindCSS:
https://tailwindcss.com/docs/adding-custom-styles#adding-custom-utilities

2023-05-05 22:05 UTC, serudda commented on apps/nextjs/src/components/Counter/Counter.tsx
> +    container: cn(className, 'counter min-w-[30px]'),
Agregaste una class: **counter** pero por ningun lado encontre los estilos? lo mismo con **count**... si no existe una class, borrar.

2023-05-06 14:05 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +/* eslint-disable @next/next/no-img-element */
Done!

2023-05-06 14:14 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +interface CardProps {
Done

2023-05-06 14:16 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +    bodyContainer: cn(
Done!

2023-05-06 14:17 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +    socialContainer: cn(
Done!

2023-05-06 14:25 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +      <img
Done!

2023-05-06 14:37 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +        {children}
Done!

2023-05-06 14:41 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> +import { setTimeout } from 'timers';
No tuve que instalar nada, esta es una dependencia global del ambiente Node.

https://github.com/nodejs/node/blob/v18.0.0/lib/timers.js

Pero como usted dice React provee una nativa y todo sigue funcionando sin el uso de esta lib.


Done!

2023-05-06 14:42 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> +    child: cn('count'),
Done. ¡Y gracias por la explicación!

2023-05-06 14:43 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> +    /**
Done!

2023-05-06 14:44 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> +   * Return an empty div for the specified delay before starting the counter
Done!

2023-05-06 14:44 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> +     * Clean up the timeout when the component unmounts
Done!

2023-05-06 14:44 UTC, Zyruks commented on apps/nextjs/src/components/Typewriter/Typewriter.tsx
> +  const classes = cn('whitespace-pre-line');
Done!

2023-05-06 14:45 UTC, Zyruks commented on apps/nextjs/src/components/Typewriter/Typewriter.tsx
> +       * Clean up the interval when the effect is cleaned up
Done!

2023-05-06 14:48 UTC, Zyruks commented on apps/nextjs/src/pages/index.tsx
> +      <main className="relative flex h-full w-full flex-none flex-col items-center justify-between gap-16  overflow-hidden bg-black p-10 ">
Done!

Si me pasa bastante que dejo un espacio por si voy a necesitar otra clase luego, pero ya lo tengo más pendiente.

2023-05-06 14:48 UTC, Zyruks commented on apps/nextjs/src/pages/index.tsx
> +        <section className=" animate-fade-in  z-10 flex flex-col items-center gap-12 text-white opacity-0 ">
Done

2023-05-06 14:51 UTC, Zyruks commented on apps/nextjs/src/styles/globals.css
> +}
Done!

2023-05-06 14:51 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> +    container: cn(className, 'counter min-w-[30px]'),
Done!

2023-05-06 15:01 UTC, Zyruks commented on apps/nextjs/src/components/Icon/Icon.tsx
> +  twitterCheck = 'M20.396 11c-.018-.646-.215-1.275-.57-1.816-.354-.54-.852-.972-1.438-1.246.223-.607.27-1.264.14-1.897-.131-.634-.437-1.218-.882-1.687-.47-.445-1.053-.75-1.687-.882-.633-.13-1.29-.083
Done!

Está muy buena la app.

2023-05-06 16:43 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +  endComments?: number;
Done!

2023-05-06 16:43 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +  endHeart?: number;
Done!

2023-05-06 16:43 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +  endRetweet?: number;
Done!

2023-05-06 16:43 UTC, Zyruks commented on apps/nextjs/src/components/Cards/Card.tsx
> +  endViews?: number;
Done!

2023-05-06 17:50 UTC, serudda requested changes

2023-05-06 17:50 UTC, serudda commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
> +  tweetText: string;
Aqui falta un comment descriptivo (en la interface si agregamos comentarios a cada prop)

2023-05-06 17:50 UTC, serudda commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
> +  commentCount: endComments = 2,
por que seguir manteniendo el "endComments"? si ya se llama commentCount, dejarlo commentCount, de type String.

2023-05-06 17:50 UTC, serudda commented on apps/nextjs/src/components/Counter/Counter.tsx
> -    container: cn(className, 'counter min-w-[30px]'),
Aqui depronto no me hice entender bien:

Todo componente tiene que tener la posibilidad de recibir classNames, del padre... por si se necesita agregar un margin o un position... asi que siempre un component deberia recibir **className** como prop... en este caso quedaria asi:

`container: cn(className),`

2023-05-06 17:50 UTC, serudda commented on apps/nextjs/src/components/Counter/Counter.tsx
> +    <div className="counter min-w-[30px]">
Si le asignas ese w-[30px] lo estas cerrando a siempre usar ese width... tienes 2 opciones:

1. Dejar con el width fijo, pero entonces Counter seria exclusivamente un componente de TweetCard.
2. Quitarle el width o volverlo parametro.

2023-05-06 17:50 UTC, serudda commented on apps/nextjs/src/components/Typewriter/Typewriter.tsx
> -  const classes = cn('whitespace-pre-line');
Lo mismo que en Counter... todo componente deberia recibir un className... asi que esta linea quedaria asi:

`const classes = cn(className, 'whitespace-pre-line');`

Aqui no se hace una asignacion dinamica, pero si necesitas el `cn` por que necesitas concatenar la prop className

2023-05-06 17:50 UTC, serudda commented on apps/nextjs/src/components/Typewriter/Typewriter.tsx
> +  return <p className="whitespace-pre-line">{currentText}</p>;
Con el comment anterior, esto volveria a estar asi:

`return <p className={classes}>{currentText}</p>;`

2023-05-06 17:50 UTC, serudda commented on apps/nextjs/src/pages/index.tsx
> +import { DottedBackground, Icon, IconCatalog, Sizes, TextGradient, TweetCard } from '~/components';
Podrias poner un TODO por fa en Icon, para que movamos los nuevos icons de twitter a `side-ui`, y asi crreamos un issue en Github, queda como deuda tecnica...

2023-05-06 18:00 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> -    container: cn(className, 'counter min-w-[30px]'),
Done!

2023-05-06 18:24 UTC, Zyruks commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
> +  tweetText: string;
Done!

2023-05-06 18:25 UTC, Zyruks commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
> +  commentCount: endComments = 2,
Hice el cambio de todo con F2 e hizo ese cambio. Qué extraño.

Done!

2023-05-06 18:25 UTC, Zyruks commented on apps/nextjs/src/components/Counter/Counter.tsx
> +    <div className="counter min-w-[30px]">
Done!

2023-05-06 18:28 UTC, Zyruks commented on apps/nextjs/src/components/Typewriter/Typewriter.tsx
> -  const classes = cn('whitespace-pre-line');
Oh entiendo, tenía mis dudas, pero ya entiendo perfectamente.

Done!

2023-05-06 19:13 UTC, Zyruks commented on apps/nextjs/src/components/Typewriter/Typewriter.tsx
> +  return <p className="whitespace-pre-line">{currentText}</p>;
Done!

2023-05-06 19:16 UTC, Zyruks commented on apps/nextjs/src/pages/index.tsx
> +import { DottedBackground, Icon, IconCatalog, Sizes, TextGradient, TweetCard } from '~/components';
Done!

2023-05-06 20:04 UTC, serudda requested changes

2023-05-06 20:04 UTC, serudda commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
> +          <Counter start={1} end={endViews} speed={25} />
por que endViews tiene otro naming? creo que lo habias renombrado a `viewCount` para mantener el estilo de las demas props que son parecidas. O me equivoco?

2023-05-06 20:04 UTC, serudda commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
>            <Counter start={1} end={endHeart} />
por que endViews tiene otro naming? creo que lo habias renombrado a `likeCount` para mantener el estilo de las demas props que son parecidas. O me equivoco?

2023-05-06 20:08 UTC, Zyruks commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
> +          <Counter start={1} end={endViews} speed={25} />
El problema de automatizar el cambio de nombre del prop.

Done!

2023-05-06 20:08 UTC, Zyruks commented on apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
>            <Counter start={1} end={endHeart} />
Done!

2023-05-06 20:23 UTC, serudda approved these changes

2023-05-06 20:24 UTC, merged